export enum ConfigKey {
  SWAGGER_BASE_PATH = 'SWAGGER_BASE_PATH',

  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASS = 'DATABASE_PASS',
  DATABASE_NAME = 'DATABASE_NAME',

  MAIL_SENDER = 'MAIL_SENDER',

  NODE_URL = 'NODE_URL',
  CONTRACT_ADDRESS = 'CONTRACT_ADDRESS',
  JUDGE_PRIVATE_KEY = 'JUDGE_PRIVATE_KEY',
}

export enum ValidationType {
  EMAIL,
}

export enum ContractEventType {
  GAME_SETUP = 'GameSetup',
  GAME_MATCHED = 'GameMatched',
}
